"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# Framework-generated: 35%
# Human-written: 30%
# AI-generated: 35%
import os
import dotenv
import django_mongodb_backend
from pathlib import Path
from datetime import timedelta
import sys

# Load environment variables from .env file
dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG') == 'True'

# Get the value from the .env file and split it into a list
# Use .get() with a default value to prevent errors if the variable isn't set
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    'app.apps.MongoAdminConfig',
    'app.apps.MongoAuthConfig',
    'app.apps.MongoContentTypesConfig',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_mongodb_backend",
        "HOST": os.environ.get('MONGO_DATABASE_HOST'),
        "NAME": os.environ.get('MONGO_DATABASE_NAME'),
        "USER": os.environ.get('MONGO_DATABASE_USER'),
        "PASSWORD": os.environ.get('MONGO_DATABASE_PWD'),
        "PORT": os.environ.get('MONGO_DATABASE_PORT'),
        "OPTIONS": {
            "retryWrites": "true",
            "w": "majority",
            "tls": os.environ.get('MONGO_DATABASE_TLS'),
            "ssl": os.environ.get('MONGO_DATABASE_SSL')
        }
    },
}

# Database routers
# https://docs.djangoproject.com/en/dev/ref/settings/#database-routers
DATABASE_ROUTERS = ["django_mongodb_backend.routers.MongoRouter"]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'

# Custom User model
# AUTH_USER_MODEL = 'api.User'  # Using UserProfile instead

MIGRATION_MODULES = {
    'admin': 'mongo_migrations.admin',
    'auth': 'mongo_migrations.auth',
    'contenttypes': 'mongo_migrations.contenttypes',
}

# CORS settings
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ORIGINS', '').split(',')

CORS_ALLOW_CREDENTIALS = True

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.authentication.CookieJWTAuthentication',  # Cookie-based JWT (secure)
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Header-based JWT (fallback)
        # Keep session auth too, if want the Django admin UI to still work
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}

# Simple JWT settings (possibly move to .env vars later)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

# JWT Cookie Settings - Secure HttpOnly cookie configuration
# These settings control how JWT tokens are stored in cookies
JWT_AUTH_COOKIE = 'access_token'  # Cookie name for access token
JWT_AUTH_REFRESH_COOKIE = 'refresh_token'  # Cookie name for refresh token

# Cookie security settings - adjusted based on environment
JWT_AUTH_COOKIE_SECURE = not DEBUG  # True in production (HTTPS only)
JWT_AUTH_COOKIE_SAMESITE = 'Lax'  # 'Strict' for maximum security, 'Lax' for usability

# Cookie max age in seconds (should match token lifetime)
JWT_AUTH_COOKIE_MAX_AGE = 60 * 60  # 1 hour (access token)
JWT_AUTH_REFRESH_COOKIE_MAX_AGE = 60 * 60 * 24 * 7  # 7 days (refresh token)


# =============================================================================
# EMAIL CONFIGURATION (for password reset)
# =============================================================================
# For development: emails print to console
# For production: configure SMTP settings in environment variables

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend'  # Default: print to console
)

# SMTP settings (for production)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@planningjam.com')

# Password reset settings
PASSWORD_RESET_EXPIRY_HOURS = int(os.environ.get('PASSWORD_RESET_EXPIRY_HOURS', 24))
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')


# Use lightweight in-memory DB for Django tests (MongoDB cannot run migrations)
if 'test' in sys.argv:
    print("Using in-memory SQLite database for tests")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }


# =============================================================================
# CONTENT SECURITY POLICY (CSP) CONFIGURATION
# =============================================================================
# CSP headers help prevent XSS, data injection, and other attacks by restricting
# which resources can be loaded and executed on the page.

CSP_ENABLED = os.environ.get('CSP_ENABLED', 'True') == 'True'

CSP_DIRECTIVES = {
    'default-src': ["'self'"],  # Only load from same origin by default
    'script-src': [
        "'self'",  # Same origin scripts
        "'unsafe-inline'",  # Inline scripts (needed for dev, should be removed in prod)
        'http://localhost:5173',  # Vite dev server (development only)
    ],
    'style-src': [
        "'self'",  # Same origin styles
        "'unsafe-inline'",  # Inline styles (needed for dev, should be removed in prod)
        'http://localhost:5173',  # Vite dev server
    ],
    'img-src': ["'self'", 'data:', 'https:'],  # Images from self, data URIs, and HTTPS
    'font-src': ["'self'", 'data:', 'https:'],  # Fonts from self, data URIs, and HTTPS
    'connect-src': [
        "'self'",  # Same origin
        'http://localhost:5173',  # Vite dev server (development)
        'http://localhost:8000',  # Django dev server
    ],
    'frame-ancestors': ["'none'"],  # Prevent embedding in iframes
    'base-uri': ["'self'"],  # Restrict base URL
    'form-action': ["'self'"],  # Restrict form submissions to same origin
}

# Adjust CSP for production if needed
if not DEBUG:
    # Remove dev server URLs and inline scripts from production CSP
    CSP_DIRECTIVES['script-src'] = ["'self'"]
    CSP_DIRECTIVES['style-src'] = ["'self'"]
    CSP_DIRECTIVES['connect-src'] = ["'self'"]


